create database joins_db;
use joins_db;

CREATE TABLE STUDENT(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50)
    );
    
CREATE TABLE ENTROLLMENT(
	STUDENT_ID INT,
	COURSE_ID INT,
	COURSE_NAME VARCHAR(20)
	);
select * from Student ;

INSERT INTO STUDENT VALUES
(1,'dhanush'),
(2,'priya'),
(3,'babu'),
(4,'siva'),
(5,'pavi');

INSERT INTO ENTROLLMENT VALUES
(1,101,'PYTHON'),
(2,102,'SQL'),
(3,103,'JAVA'),
(1,104,'DSA'),
(4,105,'SALES');
SELECT * FROM ENTROLLMENT;


SELECT S.STUDENT_ID,E.COURSE_NAME FROM STUDENT S
INNER JOIN ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;          -- inner join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM STUDENT S
LEFT JOIN ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;           -- left join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM STUDENT S
RIGHT JOIN ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;          -- right join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM STUDENT S
LEFT JOIN ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;           
UNION                                                             -- union
SELECT S.STUDENT_ID,E.COURSE_NAME FROM STUDENT S
RIGHT JOIN ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;